# Generated by Django 5.0.6 on 2024-07-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='closed',
        ),
        migrations.AddField(
            model_name='listing',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Closed',
        ),
    ]
