# Generated by Django 5.0.6 on 2024-07-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_auction_closed_listing_closed_delete_closed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auction',
        ),
    ]
