# Generated by Django 5.0.6 on 2024-07-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_delete_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
