# Generated by Django 5.0.6 on 2024-07-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_user_comment_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryListing',
        ),
    ]
